import type { Metadata } from 'next'
import './globals.css'
import { Poppins } from 'next/font/google'
import Layout from '@/components/Layout'

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ["400", "500", "700", "900"],
  style: ['italic', "normal"],
  variable: '--font-poppins'
})

export const metadata: Metadata = {
  title: 'Hotel Management App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true} suppressContentEditableWarning={true}>
      <body className={poppins.className} suppressHydrationWarning={true} suppressContentEditableWarning={true}>
        <main className='font-normal'>
          <Layout>
            {children}
          </Layout>
        </main>
      </body>
    </html>
  )
}
